name: Test PR
on:
    pull_request:
        branches:
            - main
            - "release/**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: '>=1.24.1'
            - run: go version
            - name: Install Dependencies
              run: go mod download
            - name: Build
              run: go build -v ./...

#    test:
#        needs: [ build ]
#        runs-on: ubuntu-22.04
#        steps:
#            - uses: actions/checkout@v4
#            - uses: actions/setup-go@v5
#            with:
#                go-version: '>=1.24.1'
#            - run: go version
#
#    test-complete:
#        if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
#        needs: test
#        runs-on: ubuntu-22.04
#        steps:
#            - run: |
#                  echo "Some workflows have failed!"
#                  exit 1
